<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Configurations>Debug</Configurations>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <!-- Build control -->
  <PropertyGroup>
    <SuppressTfmSupportBuildErrors>true</SuppressTfmSupportBuildErrors>
  </PropertyGroup>

  <!-- Dependencies -->
  <ItemGroup Condition="'$(TargetFramework)'=='net8.0'">
    <PackageReference Include="NUnit" Version="4.3.2" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='netcoreapp3.1'">
    <PackageReference Include="NUnit" Version="3.14.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit.Analyzers" Version="4.10.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" Version="5.2.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TeamTools.TSQL.Assistant\TeamTools.TSQL.Assistant.csproj" />
  </ItemGroup>
</Project>
